spring:
  datasource:
    url: jdbc:postgresql://localhost/spring
    username: postgres
    password: zhiger
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
