server:
  port: 8075

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    generate-ddl: false
    ddl-auto: update
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
    enabled: false

jwt:
  token:
    secret: allislamapp
    expired: 3600000



